/**
 * @license Copyright (c) 2003-2012, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.html or http://ckeditor.com/license
 */

var CKBUILDER_CONFIG = {
	skin: 'kama',
	ignore: [
		'dev',
		'.gitignore',
		'.gitattributes'
	],
	plugins: {
		a11yhelp : 1,
		about : 1,
//		adobeair : 1,
//		ajax : 1,
//		autogrow : 1,
		basicstyles : 1,
//		bbcode : 1,
		bidi : 1,
		blockquote : 1,
//		button : 1,
		clipboard : 1,
		colorbutton : 1,
		colordialog : 1,
		contextmenu : 1,
//		devtools : 1,
		dialog : 1,
		dialogadvtab : 1,
		dialogui : 1,
		div : 1,
//		docprops : 1,
		elementspath : 1,
		enterkey : 1,
		entities : 1,
//		fakeobjects : 1,
		filebrowser : 1,
		find : 1,
		flash : 1,
		floatingspace : 1,
//		floatpanel : 1,
		font : 1,
		format : 1,
		forms : 1,
		horizontalrule : 1,
//		htmldataprocessor : 1,
//		htmlwriter : 1,
		iframe : 1,
//		iframedialog : 1,
		image : 1,
		indent : 1,
		justify : 1,
		link : 1,
		list : 1,
		listblock : 1,
		liststyle : 1,
		magicline : 1,
		maximize : 1,
//		menu : 1,
//		menubutton : 1,
		newpage : 1,
		pagebreak : 1,
//		panel : 1,
//		panelbutton : 1,
		pastefromword : 1,
		pastetext : 1,
//		placeholder : 1,
//		popup : 1,
		preview : 1,
		print : 1,
		removeformat : 1,
		resize : 1,
//		richcombo : 1,
		save : 1,
		scayt : 1,
		selectall : 1,
		showblocks : 1,
		showborders : 1,
		smiley : 1,
		sourcearea : 1,
		specialchar : 1,
		stylescombo : 1,
//		stylesheetparser : 1,
		tab : 1,
		table : 1,
//		tableresize : 1,
//		tabletools : 1,
		templates : 1,
		toolbar : 1,
//		uicolor : 1,
		undo : 1,
		wsc : 1,
		wysiwygarea : 1,
//		xml : 1
	}
};
