@Library(["hackerrank-jenkins-library/ckeditor-pipelines@OP-2535"]) _

def pipelineParams = params
ckeditorPipeline {
  agentLabel             = 'hackerrank'
  repoName               = 'ckeditor-dev'
}